### ISSUE TITLE
Clarifications

### ISSUE THREAD

**Issue by deepseek** [dudeperf3ct/TextRecognizer#1]
@dudeperf3ct 
1.  How does your `Line Text Recognizer` compare to [Calamari](https://github.com/Calamari-OCR/calamari).
2. Your results for the `Line Detector` need further improvement.
Below are a suggestion of **advanced** techniques:

- [GAN Compression](https://github.com/mit-han-lab/gan-compression) [Unet based]
- [NAS-Unet](https://github.com/tianbaochou/NasUnet) [Neural Architecture search based]

    Below are a suggestion of **simpler** techniques:
- [DBNet](https://github.com/WenmuZhou/DBNet.pytorch)

Waiting for your reply

**Comment by dudeperf3ct** [comment]
@deepseek 
> 1. How does your Line Text Recognizer compare to Calamari?

 I don't know about [Calamari](https://github.com/Calamari-OCR/calamari) not sure about the comparison. In this project, I have experimented with CNN-LSTM architecture with CTC loss.

> 2. Your results for the Line Detector need further improvement.

They certainly need a lot of improvement. This project provides one case-study of how to start with a deep learning project and results of various experiments.

**Comment by deepseek** [comment]
:)
