### ISSUE TITLE
Tensorflow and Keras Version

### ISSUE THREAD

**Issue by vihar** [dudeperf3ct/TextRecognizer#2]
Hey @dudeperf3ct, thanks for code. May I know the Tensorflow and Keras version you used for this project? I've been trying to run this on Google Collab, but it giving the `tcmalloc: large alloc` error after the training starts. Also, could you share me the cloud or system configuration, you've used to run this?

Thanks :)

**Comment by dudeperf3ct** [comment]
Hey @vihar, I ran all the experiments on google colab. I am pretty sure you can just open any notebook on colab and run all the experiments except you need to change API_Key in the training file with your API_KEY. Let me know if you face any issues further.

**Comment by vihar** [comment]
Thanks @dudeperf3ct, the training is smooth on Paperspace for some reason Google Collab is giving different errors in terms of GPU memory allocation. 

Also, could you help me understand the inferencing part? I've trained my model with Custom **LineModelCTC** Model. Now I want to predict a handwritten line apart from the testing dataset, the image size has to be (28, 952) so I tried converting my own image to that particular size, but the model is giving some random results. Do you have any code snippet for that where we could test the model on our hand-written that are quite similar? 

Thanks!

**Comment by dudeperf3ct** [comment]
The [ctc notebook](https://github.com/dudeperf3ct/TextRecognizer/blob/master/Experiment-2/notebooks/exp_2_ctc.ipynb) in Experiment-2 provides an example of loading a trained model and inference on some samples from test dataset.
